// app/prisma/seed/demo/index.ts
//
// Synthetic seed database for holt. Generates the FULL native chain --
// org/settings, a complete chart of accounts, stores/registers/till
// sessions, staff with working local logins, catalog, customers, sales
// orders/payments spread across ~18 months, purchasing, a generic
// consignment vendor, commission plans + real payouts, and journal
// entries generated by calling the production `generateSalesJournal()` --
// so a fresh `holt` clone has something real to look at instead of an
// empty database or the importer's artifact-laden dataset.
//
// See docs/domains/seed-data.md for the full writeup: what each module
// generates, the distribution choices, and why.
//
// USAGE (from app/):
//   TZ=UTC DATABASE_URL=postgresql://...@localhost:5435/holt_seed_demo \
//     npm run seed:demo
//
// Volume:      HOLT_SEED_SCALE=ci|demo (default ci), or --scale=demo
// Reset:       --reset  (wipes every seeded row and reseeds; refuses to
//              run at all against an existing dataset without it)
// Date anchor: HOLT_SEED_AS_OF=YYYY-MM-DD (default 2026-08-01), or --as-of=
// DB safety:   --force-unsafe-db / HOLT_SEED_FORCE_UNSAFE_DB=1 to target
//              saybrook / holt_saybrook / akritos / fbc_dev_db. fbc_test_db
//              can never be targeted, override or not (rule 59).
//
// Deterministic: every run with the same scale + as-of date produces
// byte-identical rows (fixed RNG seed -- see config.ts ROOT_SEED_STRING).

process.env.TZ = "UTC"; // MUST be first -- see journal.ts's header comment.

import { assertSafeSeedTarget, maskDatabaseUrl } from "./guard";

const argv = process.argv.slice(2);

async function main(): Promise<void> {
  const databaseUrl = process.env.DATABASE_URL ?? "";
  const forceUnsafe =
    argv.includes("--force-unsafe-db") || process.env.HOLT_SEED_FORCE_UNSAFE_DB === "1";
  const dbName = assertSafeSeedTarget(databaseUrl, { forceUnsafe });

  // Imported AFTER the safety check so a refused target never even
  // constructs the shared Prisma singleton's connection pool against it.
  const { prisma } = await import("@/lib/prisma");
  const { TABLES_FOR_TEST_RESET } = await import("@/lib/testing/withTestDb");
  const { makeRng } = await import("./rng");
  const { ROOT_SEED, resolveVolume, resolveScale, seedWindow } = await import("./config");
  const { seedOrg } = await import("./org");
  const { seedAccounting } = await import("./accounting");
  const { seedLocations } = await import("./locations");
  const { seedStaff } = await import("./staff");
  const { seedCatalog } = await import("./catalog");
  const { seedCustomers } = await import("./customers");
  const { seedCommissionPlans } = await import("./commissionPlan");
  const { seedSalesOrdersAndTills } = await import("./salesOrders");
  const { seedPurchasing } = await import("./purchasing");
  const { seedConsignment } = await import("./consignment");
  const { seedInventory } = await import("./inventory");
  const { seedService } = await import("./service");
  const { seedOperations } = await import("./operations");
  const { seedCommissionPayouts } = await import("./commissionPayouts");
  const { seedJournalEntries } = await import("./journal");
  const { ORG_SLUG } = await import("./org");

  const scale = resolveScale(argv);
  const volume = resolveVolume(argv);
  const window = seedWindow(argv);
  const reset = argv.includes("--reset");

  console.log(`holt demo seed — target "${dbName}" (${maskDatabaseUrl(databaseUrl)})`);
  console.log(
    `scale=${scale} window=${window.start.toISOString().slice(0, 10)}..${window.end.toISOString().slice(0, 10)}`,
  );

  const existingOrg = await prisma.organization.findUnique({ where: { slug: ORG_SLUG } });
  if (existingOrg && !reset) {
    console.error(
      `Seed data already exists (Organization "${ORG_SLUG}", id ${existingOrg.id}). ` +
        `Re-run with --reset to wipe every seeded row and reseed from scratch, or point ` +
        `DATABASE_URL at a fresh database. Refusing to half-seed on top of existing data.`,
    );
    process.exit(1);
  }
  if (existingOrg && reset) {
    console.log("Existing seed data found — --reset passed, truncating every table first...");
    const quoted = TABLES_FOR_TEST_RESET.map((t) => `"${t}"`).join(", ");
    await prisma.$executeRawUnsafe(`TRUNCATE TABLE ${quoted} RESTART IDENTITY CASCADE;`);
    console.log("Truncated. Reseeding...");
  }

  const rng = makeRng(ROOT_SEED);

  const org = await seedOrg(prisma);
  const accounting = await seedAccounting(prisma);

  // AppSettings.defaultTaxDistrictId is resolveTaxRate.ts's last-resort
  // fallback (CLAUDE.md rule 61 -- this used to be the hardcoded
  // `shortName: "CT"` literal in create-from-cart.ts / import-hd-proposal.ts).
  // Set here, after seedAccounting creates the CT district and before
  // anything prices a sale, so a fresh `npm run setup` still charges tax
  // even for an order whose store/customer resolve to nothing more specific.
  await prisma.appSettings.update({
    where: { organizationId: org.organizationId },
    data: { defaultTaxDistrictId: accounting.taxDistrictId },
  });

  const locations = await seedLocations(prisma, accounting.taxDistrictId);
  const staff = await seedStaff(
    prisma,
    locations.stores,
    locations.stores[0]?.id ?? 0,
    volume.designerCount,
  );
  const catalog = await seedCatalog(
    prisma,
    rng,
    accounting.accountGroupIdByDepartment,
    volume.productCount,
  );
  const customers = await seedCustomers(
    prisma,
    rng,
    accounting.taxDistrictId,
    accounting.taxExemptReasonIdByName.get("Resale")!,
    volume.customerCount,
  );
  const commissionPlans = await seedCommissionPlans(prisma);

  // Assign the two most senior designers to the richer plan so the seed
  // demonstrates per-staff plan overrides, not just the default.
  for (const designer of staff.designers.slice(0, 2)) {
    await prisma.staffMember.update({
      where: { id: designer.id },
      data: { commissionPlanId: commissionPlans.seniorPlanId },
    });
  }

  const salesResult = await seedSalesOrdersAndTills(
    prisma,
    rng,
    window,
    volume.orderCount,
    locations.stores,
    staff,
    customers,
    catalog.products,
    accounting.taxDistrictId,
  );

  const purchasingResult = await seedPurchasing(
    prisma,
    rng,
    window,
    catalog.products,
    locations.stores,
    staff.warehouseStaff,
    volume.purchaseOrderCount,
  );

  const consignmentResult = await seedConsignment(
    prisma,
    rng,
    window,
    locations.stores,
    volume.consignmentItemCount,
  );

  // On-hand stock. After purchasing, so the catalog and locations both exist,
  // and the committed-stock positions can hang off real sales orders.
  const committedOrders = await prisma.salesOrder.findMany({
    where: { status: "ORDER" },
    select: { id: true, storeLocationId: true },
    take: 25,
    orderBy: { id: "desc" },
  });
  const inventoryResult = await seedInventory(
    prisma,
    rng,
    catalog.products,
    locations.stores,
    locations.warehouseStockLocationId,
    locations.warehouseCommittedStockLocationId,
    locations.warehouseStoreLocationId,
    committedOrders,
  );

  const serviceResult = await seedService(
    prisma,
    rng,
    customers,
    staff,
    locations.stores,
    volume.serviceCaseCount,
  );

  const operationsResult = await seedOperations(
    prisma,
    rng,
    org.organizationId,
    customers,
    staff,
    locations.stores,
    volume.ticketCount,
    volume.timeEntryCount,
  );

  const commissionPayoutsResult = await seedCommissionPayouts(window);

  const journalResult = await seedJournalEntries(prisma);

  console.log(
    `Inventory: ${inventoryResult.positionsCreated} positions, ${inventoryResult.unitsOnHand} units on hand ` +
      `(${inventoryResult.committedPositions} committed to orders, ` +
      `${inventoryResult.productsWithNoStock} products never stocked)`,
  );
  console.log(
    `Service: ${serviceResult.casesCreated} cases (${serviceResult.openCases} open), ` +
      `${serviceResult.notesCreated} notes, ${serviceResult.typesCreated} case types`,
  );
  console.log(
    `Helpdesk: ${operationsResult.ticketsCreated} tickets (${operationsResult.openTickets} open), ` +
      `${operationsResult.ticketMessages} messages`,
  );
  console.log(
    `Time: ${operationsResult.timeEntries} entries (${operationsResult.unbilledMinutes} unbilled minutes), ` +
      `${operationsResult.shiftsCreated} shifts (${operationsResult.openShifts} open)`,
  );
  console.log("");
  console.log("=== Seed complete ===");
  console.log(`Organization: ${org.organizationId} (${ORG_SLUG})`);
  console.log(
    `Stores: ${locations.stores.length}, Registers: ${locations.stores.reduce((s, x) => s + x.registerIds.length, 0)}`,
  );
  console.log(
    `Staff: ${staff.all.length} (${staff.designers.length} designers, ${staff.registerStaff.length} register, ${staff.warehouseStaff.length} warehouse)`,
  );
  console.log(`Products: ${catalog.products.length}, Customers: ${customers.length}`);
  console.log(`Orders: ${salesResult.ordersCreated}, Invoices: ${salesResult.invoicesCreated}`);
  console.log(
    `Payments: ${salesResult.paymentsCreated} (refunds: ${salesResult.refundPaymentsCreated}, returns: ${salesResult.returnsCreated}), method mix:`,
    salesResult.methodCounts,
  );
  console.log(`Gift cards issued: ${salesResult.giftCardsCreated}`);
  console.log(`Tills closed: ${salesResult.tillsClosed}, open: ${salesResult.tillsOpen}`);
  console.log(
    `Forced till variances -> note:${salesResult.forcedVariance.note} manager:${salesResult.forcedVariance.manager} escalation:${salesResult.forcedVariance.escalation} (blocked register ${salesResult.blockedRegisterId})`,
  );
  console.log(
    `Purchase orders: ${purchasingResult.purchaseOrdersCreated}, receiving records: ${purchasingResult.receivingRecordsCreated}`,
  );
  console.log(
    `Consignment items: ${consignmentResult.itemsCreated} (vendor ${consignmentResult.vendorId})`,
  );
  console.log(
    `Commission payouts: ${commissionPayoutsResult.payoutsCreated} across ${commissionPayoutsResult.periodsProcessed} periods (${commissionPayoutsResult.payoutsLocked} locked)`,
  );
  console.log(
    `Journal entries: ${journalResult.entries.length} for days [${journalResult.daysProcessed.join(", ")}]`,
  );
  for (const e of journalResult.entries) {
    console.log(
      `  ${e.journalNumber} (${e.date}): debits=${e.totalDebits.toFixed(2)} credits=${e.totalCredits.toFixed(2)} balanced=${e.totalDebits === e.totalCredits}`,
    );
  }
  if (journalResult.warnings.length > 0) {
    console.log(`Journal warnings (${journalResult.warnings.length}):`);
    for (const w of journalResult.warnings) console.log(`  - ${w}`);
  } else {
    console.log("Journal warnings: none — every payment type and account-group leg mapped.");
  }

  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
